<?php

namespace AppBundle\Repository;

/**
 * OlympicsMedalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OlympicsMedalsRepository extends \Doctrine\ORM\EntityRepository
{
}
